sudo: required
services:
- docker
env:
  global:
  - IMAGE_NAME=soniaauvets/airflow-ros-tensorflow
before_script:
- version="$(cat VERSION)"
script:
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" --build-arg GCLOUD_SERVICE_ACCOUNT_EMAIL="${GCLOUD_SERVICE_ACCOUNT_EMAIL}"
  .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
deploy:
- provider: script
  script: docker tag "$IMAGE_NAME" "${IMAGE_NAME}:dev" && docker push "${IMAGE_NAME}:latest"
    && docker push "${IMAGE_NAME}:dev"
  on:
    branch: dev
- provider: script
  script: docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}" && docker push "${IMAGE_NAME}:latest"
    && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
notifications:
  slack:
    secure: M0XLvuBfNt6peupJ+kAyI6wtmLra3ESETGRLWfFpk6bqiqFfSMm9o76+BVpq3S06wfmR3xok8ehnOdSoMk2ktnIdESay4hK4kMONadbEAlnamveghfrXaqdLpvFwcBLsbtDhul8ZeDYfZC8YQu2RfptVzTUexP1hmJN0D/bq4B2FDZZIk8L0HrYL2Gu+l5U/Ua4ddeWq0v3fICR0mr3LzYGRN+LPCod6kykIbhc4nzYkCikRSRsADIVN/lpKvbJ+GLevzvRKBhNs8NLdIq1V8VhNi7PLBMyvVBdbK3hYkVN7RQGvlSkeBY8WH7Fj8upkzzVPsol6d44ln0c0jUeO1SL1Pnfet1pSZqbCvldXejlQaXVZ8rV7u6v1qTsdwG5bIKDRpmz1nrjaTPsfz7lpfULCGw77ZoC+Tlf8oCwvgj0KcqhYdNY+3V3COcMXuCipmssJhhbhH5rnaXxISdSyNujj+JinDWcFUI26BY0kz9BnijL/EXDNqV5bJNYwwz+++XY6O6h9LK/qUDvFLqKBdJhIDUycDWv1mbaZa+yhMH1feH6FzcOur0zFJOhWFHA/LnWA0g+KZ80a5AA8nzOD7b4ce20a3PmaNdXhTkKo+4ya40J4xPwtNpXkIv3WEij8vbUuLcLbBdXjwxrZBAw3Kl6gl8XZ/pKsXvi07d/0bvE=
