version: "3.7"
services:
  airflow-webserver:
    volumes:
      - ${AIRFLOW_DAG_DIR}:/usr/local/airflow/dags
      - $PWD/data:/usr/local/airflow/data
      - $PWD/logs:/usr/local/airflow/logs
      - $PWD/config/gcloud_service_account.json:${AIRFLOW_HOME}/gcloud_service_account.json
      - /var/run/docker.sock:/var/run/docker.sock
