version: "3.1"
services:
  airflow-postgres:
    image: postgres:9.6
    hostname: airflow-postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-log:/var/log/postgresql

  airflow-webserver:
    image: ${AIRFLOW_DOCKER_IMAGE_NAME}:${AIRFLOW_DOCKER_IMAGE_TAG}
    hostname: airflow-webserver
    restart: always
    depends_on:
      - airflow-postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - AIRFLOW_FERNET_KEY
    volumes:
      - $AIRFLOW_DAG_DIR:/usr/local/airflow/dags
      - $PWD/data:/usr/local/airflow/data
      - $PWD/logs:/usr/local/airflow/logs
      - gcloud-config:/usr/local/airflow/.config/gcloud
      - ssh-keys:/home/airflow/.ssh

    ports:
      - "4080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  pg-data: {}
  pg-log: {}
  gcloud-config: {}
  ssh-keys: {}
