name: Docker Build
on:
  push:
    branches:
      - master
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: test
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        repository: jerray/publish-docker-action
