name: Docker Build
on:
  push:
    branches:
      - master
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: test
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: jerray/publish-docker-action
