name: Main
on:
  - push
  - create
jobs:
  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sonia-auv/airflow-etl
          auto_tag: true
