name: Docker Build

jobs:
  runs-on: ubuntu-latest
  uses: jerray/publish-docker-action@1.
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    registry: docker.pkg.github.com
    repository: jerray/publish-docker-action
