name: Publish Docker (feature)
on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sonia-auv/airflow-etl/airflow-etl
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
